# Generated by Django 4.1.2 on 2023-07-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0011_alter_inventario_id_coleccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('categoria', models.CharField(max_length=32)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
