# Generated by Django 4.1.2 on 2023-07-07 00:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0012_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/IMG'),
            preserve_default=False,
        ),
    ]
